### ISSUE TITLE
[Issue] Model becomes invisible upon glTF export, no export occurs

### ISSUE THREAD

**Issue by dranorter** [JannisX11/blockbench#1120]
I'm trying Blockbench for the first time, just downloaded version 4.0.1, and I made a simple model (generic - I'm trying to use this in another game engine) with a very simple walk cycle and tried to export it as glTF. No "Save as" dialogue appeared, and the model became invisible. While invisible, everything seems to function as if it were there -- I can paint on it, rearrange it etc. But nothing I've found makes it visible again. Saving the project, closing, and re-loading restores full visibility.

No export occurs.

Operating system: Windows 10

The project: (dropbox) https://www.dropbox.com/s/nzwd97kg12760cj/firsttry.bbmodel?dl=0

It's a very simple model, just a few squashed cube meshes:
![image](https://user-images.githubusercontent.com/14154658/137794049-cd1fdfc3-3fad-4f59-aa4d-214d70c8bbb1.png)

In the console, the following error appears.

![image](https://user-images.githubusercontent.com/14154658/137794012-7764901e-7ea3-4140-9e4f-21b50e8fe05d.png)

**Comment by dranorter** [comment]
The error seems to be that "mesh.geometry.faces" is undefined.

**Comment by pifase** [comment]
I have similar issues except that I'm trying to save my Model as a Java file

**Comment by dranorter** [comment]
@pifase , would you mind uploading your file? I want to see if it acts the same way on my machine.

**Comment by dranorter** [comment]
I mean the project file.

**Comment by dranorter** [comment]
It's not precisely the same error, and for me the model didn't become invisible. Here's the error I got.

![image](https://user-images.githubusercontent.com/14154658/138187107-b5577a79-3ec0-496e-9102-07ff9f5cce38.png)

**Comment by Joetriana** [comment]
hello, i'm leaving a comment cause i'm having the same issue as of 11/04/2021. When trying to export the model to a gltf model no "save" window appears and the model itself becomes invisible. here's the error i got.
![error capture](https://user-images.githubusercontent.com/20331680/140269162-2698fe61-1b83-4890-965a-3b77392a61b1.PNG)
i also discovered that converting the project to anything other than a generic model project makes it possible to export to gltf again. so the bug seems to only affect  generic model projects
