### ISSUE TITLE
[Suggestion] Be Aware of Feature Creep

### ISSUE THREAD

**Issue by audinue** [JannisX11/blockbench#1147]
I'm surprised that since 4.0.0 (The Mesh Update) we can edit poly in Blockbench.

Now, that's a pretty huge thing if you know what I mean.

Subdivide, loop cut, knife, boolean operations, mirror editing to name a few.

I hope that Blockbench keep it's identity as a **boxy** 3D model editor, not another LightWave or Blender.

Thank you.

**Comment by ellogwen** [comment]
I don't think that low poly modelling is so much out of the scope of this software. Box modelling functionality is, afaik, a part of the THREE.js framework anyway. So it was "just" used. Even more, I am very happy, because the old way of doing required a lot of overlapping and clipping geometry to do certain things. Tbh, I whish they would add boolean operations to easier create gabs and holes in existing geometries instead of creating a dozen boxes to accomplish the same as a simple boolean substraction.

So, thank you Jannis for adding box/mesh modeling.

**Comment by JannisX11** [comment]
> I hope that Blockbench keep it's identity as a boxy 3D model editor, not another LightWave or Blender.

The reality is in between the two. Now that meshes are supported, Blockbench is a **low-poly** model editor. Before Blockbench, there was no other program available that focused on low-poly models, especially with pixel-art textures, and made them easy to work with.

**Comment by audinue** [comment]
> > I hope that Blockbench keep it's identity as a boxy 3D model editor, not another LightWave or Blender.
> 
> The reality is in between the two. Now that meshes are supported, Blockbench is a **low-poly** model editor. Before Blockbench, there was no other program available that focused on low-poly models, especially with pixel-art textures, and made them easy to work with.

Thank you :)
