### ISSUE TITLE
[Issue] re-importing an animation made with the ik system leaves the model in the bind pose

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1219]
-Making an animation with the new IK system (positioning the null object), saving, unloading, then re-importing the animation causes the bones to stay in the bind pose when trying to play the animation.

Updating the values in the keyframes does not change anything, I found that only closing the tab and re-opening the model worked.

https://user-images.githubusercontent.com/81629481/147012088-a55810b9-45de-486f-9105-bedd9a128fcd.mp4

-Blockbench 4.1.0, Windows 10

**Comment by JannisX11** [comment]
Works as intended because after re-importing the bones are still part of an active IK chain due to the null object existing. The IK chain overrides keyframe values of the individual bones.
Also note that MC bedrock models and animations do not support IK natively, so if you want to keep your IK chains and animations for later editing, you need to save as .bbmodel.
