### ISSUE TITLE
Deletion of Computer Files while using Blockbench

### ISSUE THREAD

**Issue by Arcane-Net** [JannisX11/blockbench#1260]
To start off with I was unaware Blockbench could even do this to my device. I am sure you are unaware of this as well but it is a serious issue that needs addressed. It started when I went to edit 2 textures for my Blockbench models. I had 2 models with separate textures and I wanted to combine the models and use a combined image of both textures so I wouldn't have to remake a whole new image. After   I edited the image and save it as something else, everything broke. I loaded up Blockbench to see that my models I was going to combine with the same texture were blank, their textures were gone. I thought well this is not a big deal since I have the combined texture for them now but then I couldn't see my Models folder. My models folder is located under downloads and I am not really sure how editing an image by combining two textures could delete months of hard work. In total I lost 20 Models, the Backup folder only backs the models up within a certain time frame. This is very serious because the folder was not located under Blockbench directory but under downloads. It appears to have completely wiped the files from my device as I cannot find them under the recycle bin. Finally just wanted to say I really enjoy Blockbench and created a lot of cool stuff with this amazing program but I cant trust something if it has a chance of doing this. 

- As far as I can tell has not been reported before or at least I hope no one else has had this terrible issue
- Blockbench version 4.1.3 (up to date)
- Windows 10

**Comment by Degagelemming** [comment]
Well my reason for believing BlockBench is responsible is because only thing I was dealing with at the time and there were no computer crashes or other anomalies. I am also using Blockbench without any plugins let alone non supported ones. I checked thru all my computer files but I couldn’t find it so what may have happened was when I was editing the texture that was saved in my models folder it must have somehow messed with the textures already loaded for those models causing a deletion. I’m not really sure how that can happen or why it would effect it but that’s the only thing I can think of.

**Comment by SOSAGEYO** [comment]
I encountered the same problem after updating blockbench from version 7 to the latest. I worked in it for a while and turned off the computer. As a result, the next day, all my models were deleted, the folders with the separation of textures and scripts were in place, but all the files inside them were deleted.
Only 1 model survived, and only because it was archived and in the trash.

It was unpleasant to lose a bunch of models I made
