### ISSUE TITLE
[Issue] Inputing position via keyboard breaks the model

### ISSUE THREAD

**Issue by MedicalJewel105** [JannisX11/blockbench#1538]
Blockbench 4.3.1 Desktop (Windows 64), bedrock entity (not sure about other formats), no console errors.
You can input data into position fields when editing the model by 2 ways: 1 - using mouse, 2 - using keyboard (then you click somewhere outside or hit enter).
If you use keyboard for moving a group of cubes, some of them do not move, move move less than others or appear somewhere they should not be. Selecting the text in position box (even if it is 0), has the same effect. Ctrl + z helps to revert this.

https://user-images.githubusercontent.com/87320205/186289832-2c27bb70-1122-458b-83e8-84d3133143aa.mp4

**Comment by JannisX11** [comment]
Entering a position value moves all elements to that coordinate, which is typically not what you want, since the elements are supposed to be in different positions.
If you want to move your model, use the transform gizmo (the 3 colored arrows in the viewport), or enter a relative position value into the position field, e. G. `+5`.
