### ISSUE TITLE
[Issue] outline rendering

### ISSUE THREAD

**Issue by x-yingcan-x** [JannisX11/blockbench#1572]
![OutlinRenderissue](https://user-images.githubusercontent.com/99530733/190867144-1e24fac1-95b8-4de5-8817-3d4cb07c72ce.png)
![OutlinRenderissue1](https://user-images.githubusercontent.com/99530733/190867166-696d7b98-b2d3-4367-8531-df96a4211cd8.png)
As you can see, the rendering of the model's outline is strange
No warning, restarting doesn't help.I don't know what's causing it (mechanical translation, sorry)
java block/item
blockbench 4.4.1
Window 7

**Comment by x-yingcan-x** [comment]
I can accept the problem with models like the "sword" one, which can happen in vanilla, but the "pickaxe" one is strange.
And this kind of error doesn't always happen, it only happens when you look at the model from a certain angle

**Comment by JannisX11** [comment]
From the Discord FAQ:

If you see thin lines on some edges of your model that should not be there, that is caused by an effect called Texture Bleeding. Some of the color of the neighboring pixels on the texture are visible where they should not be. In most cases, this artifact is caused by anti aliasing (MSAA), a technique to smooth the edges of your model in the render.
There are several ways to solve this:

*  If you just want to get rid of the lines in the Blockbench preview or in screenshots, you can disable "Anti Aliasing" in the Blockbench settings. Make sure to restart the program after changing the setting.
*  If you want to export your model into Minecraft or another game or application, the effect is often less (and sometimes more) noticeable. To fix it in the model, install the Blockbench plugin Plaster, then select the cubes you want to fix and go to Filter > Plaster. This does not work in Box UV mode.
*  Another way to preemptively reduce texture bleeding is to leave a gap between your UV sections. The Blockbench template generator comes with a "Padding" option that let's you do this.
