### ISSUE TITLE
[can't see and thing in wrokspace in mac] when I open Blockbench the models , arrows and the grid can't be seen in mac

### ISSUE THREAD

**Issue by binugamez** [JannisX11/blockbench#1617]
In macOs hight sierra the block bech is not showing the models , grids and and axis arrows and and tool arrows but we can still paint on it so pls fix it I want to make some fun mobes again :(

**Comment by JannisX11** [comment]
Cannot reproduce. Maybe your graphics card is too old and no longer compatible with Blockbench.

**Comment by binugamez** [comment]
same with my imac

**Comment by JannisX11** [comment]
Chromium blacklists Intel HD Graphics 3000 series due to frequent crashes on MacOS: https://source.chromium.org/chromium/chromium/src/+/main:gpu/config/software_rendering_list.json;l=1?q=software_rendering_list&sq=&ss=chromium
I assume the same happens with integrated Nvidia graphics chips of the same generation.

Unfortunately there is nothing I can do.
I have updated the minimum hardware requirements on the Blockbench download page to reflect this.

**Comment by binugamez** [comment]
this is my mac deatils

![my mac deattils](https://user-images.githubusercontent.com/116512066/212102361-af86ec42-505d-42db-af06-23d1e3855e05.png)

cheke again pls is it my display

**Comment by binugamez** [comment]
it been almost a day I told my mac deatls , now we have a good news and bad news

good news : I can see stuff in my mac's work space again :)

Bad news : it happen again all back to squre 1 :(
