### ISSUE TITLE
[Suggestion] [Modded Entity] Use the blocks pivot point when using the inflate value

### ISSUE THREAD

**Issue by Magicmaan** [JannisX11/blockbench#1636]
Current behaviour of the inflate tool is, independent of any group or pivot, changes the scale of the cube based on its personal centre. This makes it near impossible to use when trying to inflate/deflate multiple cubes or groups and align them.

What i suggest is, each block will inflate and be moved based on the blocks pivot point. This would make it far more usable and would be in line with other tools behaviour

**Comment by JannisX11** [comment]
Inflate is a specific property that comes from Minecraft and can be used for example to create a second layer around existing cubes, such as the clothing layer on players. It grows the element in each direction by a certain fixed value. Don't get it confused with Scaling, which can be accessed from Transform > Scale (but doesn't work well with modded entities due to technical limitations).
