### ISSUE TITLE
[Issue] particle dynamic acceleration z axis is inverted

### ISSUE THREAD

**Issue by PaulFinnerty** [JannisX11/blockbench#1771]
### Detailed description of your issue

It seems like the value on the Z axis for acceleration is inverted compared to Snowstorm (correct in Snowstorm, incorrect in Blockbench)

https://user-images.githubusercontent.com/81629481/222033231-2a0c3a0c-7f28-423b-92c7-784fc1527504.mp4

### Model format in which the issue occurs

Bedrock entity

### Blockbench variant

Program

### Operating System

Windows 10

**Comment by JannisX11** [comment]
This is because Snowstorm defaults to displaying the particles in world space, while Blockbench displays them in entity space by default.
You can switch Snowstorm to entity space in the preview bar below the viewport.
Coordinate directions are generally pretty inconsistent in Minecraft Bedrock Edition. Locator space also has different rules.
