### ISSUE TITLE
[Issue] Issue with displaying textures in GIF

### ISSUE THREAD

**Issue by DUNKAN404** [JannisX11/blockbench#1865]
### Detailed description of your issue

I drew a model of a droid and then animated it. When I applied the texture and recorded the GIF, I saw this bug.
![gnk_test2](https://user-images.githubusercontent.com/73896685/236047425-87b1da50-710a-48a3-a34d-a467f2a4b701.gif)

### Model format in which the issue occurs

Generic Model

### Blockbench variant

Program

### Operating System

windows

**Comment by PaulFinnerty** [comment]
The flickering is caused by the automatic compression of the GIF.

If you want better quality, install the "Scene Recorder" Plugin, by going to File > Plugins > Available. Then instead of going to View > Record GIF, use View > Record Scene. It will provide you with more options, including GIF, except it will be of a much better quality.
