### ISSUE TITLE
[Suggestion] Angles that aren't a factor of 22.5 and Edge snapping

### ISSUE THREAD

**Issue by BrownBoiiWonder** [JannisX11/blockbench#187]
Angles are too restrictive and model editors/makers like Tabula and even techne support a full 180 degree spectrum. Changing angles could also be done without having to leave the part like how it can be moved around or resized without having to necessarily change the values manually in the toolbar.

Edge snapping would be nice because vertex snapping isn't the best option all the time especially when you have 1 part right where you want it but just need it to snap/connect to the edge of another part with ease.

**Comment by JannisX11** [comment]
Rotation restrictions can be disabled in the settings. They are enabled by default because most people use Blockbench to create models for Minecraft Java Edition, where rotations are limited to one axis and 22.5° increments.

Multiple suggestions one one post don't work well together with the Github issue system. Please create a seperate issue for each suggestion.

**Comment by BrownBoiiWonder** [comment]
Not sure that's the case when models made in iChun's Tabula mod have no issues when used in Java Edition

**Comment by JannisX11** [comment]
As far as I know Tabula creates models for mods in a .java format. Blockbench uses the new item/block .json format added in 1.8 that works differently and doesn't require mods.

**Comment by Leroidesafk** [comment]
> Not sure that's the case when models made in iChun's Tabula mod have no issues when used in Java Edition



> 

where is the settings for fix it ?
