### ISSUE TITLE
Can't install on Linux. Conflict with electron?

### ISSUE THREAD

**Issue by YTFrost** [JannisX11/blockbench#1915]
### What are you trying to do, and what do you expect to happen?

I am trying to install Blockbench from the Arch User Repository on my PC, running EndeavourOS Cassini Nova 03-2023 R2, on kernel version 6.3.8-arch1-1 64-bit. When I attempt to `sudo yay -s blockbench`, I expect blockbench to compile and install on my system.

### What happens instead?

I get the following error message:
`error: failed to commit transaction (conflicting files)
blockbench: /usr/lib/electron exists in filesystem (owned by electron)
Errors occurred, no packages were upgraded.`

### Model format in which the issue occurs

N/A

### Blockbench variant

Program

### Operating System

EndeavourOS

**Comment by JannisX11** [comment]
I'm afraid there is nothing I can do to help, except google the error message for you. I also don't have much experience with Linux.
The Arch User Repository is a user-submitted version of Blockbench, not an officially supported version. Regardless, the issue is probably in Electron, or in the configuration of your system, or the user-submited AUR package, Not in Blockbench itself.
