### ISSUE TITLE
Cannot Read Properties Of Null

### ISSUE THREAD

**Issue by stormcop** [JannisX11/blockbench#1955]
### What are you trying to do, and what do you expect to happen?

im trying to open blockbench

### What happens instead?

it says "uncaught type error cannot read properties of null (reading inside_vue)"

### Model format in which the issue occurs

Blockbench

### Blockbench variant

Program

### Blockbench version

4.7.4

### Operating System

64 bit Acer

**Comment by JannisX11** [comment]
This is caused by an item in one of the toolbars that does not load correctly.
As a temporary fix, you can reset your toolbars:

1. Open the console: `Ctrl + Shift + i`, then click Console
2. Paste this to reset your toolbars: `localStorage.removeItem('toolbars')`
3. Confirm via Enter
4. Restart Blockbench

**Comment by stormcop** [comment]
thank you
