### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by EpicMidtoker6** [JannisX11/blockbench#2062]
### What are you trying to do, and what do you expect to happen?

Try to make an edit session

### What happens instead?

No token is formed and the only way to quit is to close the model

### Model format in which the issue occurs

Any

### Blockbench variant

Program

### Blockbench version

4.8.3

### Operating System

Windows

**Comment by alexzander700** [comment]
Steps to reproduce, and images since I'm also having the same issues:

Create the Session:
![image_2023-12-01_190351388](https://github.com/JannisX11/blockbench/assets/51793351/35bb01ed-34d2-422d-9e12-dd1a683585fd)

Look back at the session info:
![image](https://github.com/JannisX11/blockbench/assets/51793351/0a189716-ab4b-4d85-8470-17122040bfb9)

There should be Token Info, but there isn't.

**Comment by alexzander700** [comment]
The reason for using the session is that I need to collab with others for specific skins, so any solutions would be great to have sooner rather than later. Thank you for the help.
