### ISSUE TITLE
Unable to use after each automatic update.

### ISSUE THREAD

**Issue by GouLiGuoJiaNaive** [JannisX11/blockbench#216]
[image](https://user-images.githubusercontent.com/30216016/50573935-74050200-0e18-11e9-8e4e-08b4957cb408.png)

**Comment by yamina-chan** [comment]
I have the same issue after the latest update. 
![uh](https://user-images.githubusercontent.com/39206316/50611011-34502000-0ed5-11e9-963f-45aa665d8883.PNG)
It still worked imediately after the update. Since then I've shut down the PC and today is the first time after that fact that I tried to open Blockbench and was instead greeted with...well... this.
A manual new installation of the most recent version has fixed the program from whatever went wrong in the auto update.

**Comment by JannisX11** [comment]
Closed due to inactivity.
