### ISSUE TITLE
Is there a way to select an element in the 2D paint view?

### ISSUE THREAD

**Issue by mcrimson974** [JannisX11/blockbench#2242]
Select element in 2D paint view

I'm in Paint mode, I want to make a selection in the 2D paint view with the Selection Tool to select an element. How can we do that?

**Comment by JannisX11** [comment]
The selection tool selects parts of the texture, not elements. If you are looking to select (and transform) a layer, you can use the Move Layer tool. Otherwise, use the selection tool by dragging a selection.

The Github page is for suggestions and bug reports, for questions, please use the Discord server.
