### ISSUE TITLE
[Issue] Json is too large and the software crashes

### ISSUE THREAD

**Issue by fvffv** [JannisX11/blockbench#229]
hello，
I used some software to convert the schematic into JSON for the software to read
After a while, the software interface disappears, with only one window
What I can confirm is that JSON is fine and can be read with smaller JSON
JSON download address: [...]

**Comment by JannisX11** [comment]
The model contained more than 60 thousand elements which is way too much for one model. The solution is: don't use that generator. If you create models efficiently by hand, you can have very beautiful and detailed models with far less than 1000 cubes.

By the way, I will remove the link since it contains a suspicious executable.
