### ISSUE TITLE
Option to move selected keyframes by random values to add timing variety.

### ISSUE THREAD

**Issue by thePixelmancer** [JannisX11/blockbench#2572]
### Detailed description of your suggestion

Would be nice to have a simple option that would allow us to offset keyframes randomly. Often when animating pose to pose, its nice to give random offsets to some keyframes to easily make the animation more visually interesting, especially if the model requires somewhat random movement, such as tentacles, monster arms, tails, etc...
A slight variance in delay makes the animation feel extra polished and is a task that could easily be automated.

**Comment by JannisX11** [comment]
You can do this by typing `+math.random(-0.2, 0.2)` into the keyframe time slider.
See [Blockbench Overview & Tips > Sliders](https://www.blockbench.net/wiki/guides/blockbench-overview-tips/#sliders)

I think it's too niche of a use-case to warrant a dedicated button, especially since it's already relatively easy via expression.
