### ISSUE TITLE
model saving wrong won't export

### ISSUE THREAD

**Issue by mjsmom2012** [JannisX11/blockbench#2573]
### What are you trying to do, and what do you expect to happen?

my daughter is taking a class with BB.  She is supposed to save her model and have it export as a zip file.  She is then to upload it to Mixamo.  

### What happens instead?

It only saves as a blockbench project or OBJ wavefront model.  So there is nothing to unzip and it won't upload to Mixamo.  

### Model format in which the issue occurs

generic model

### Blockbench variant

Program

### Blockbench version

4.11.2

### Operating System

windows 10 home

**Comment by JannisX11** [comment]
Blockbench supports multiple export formats. Which one are you using?

**Comment by mjsmom2012** [comment]
Obj

**Comment by JannisX11** [comment]
The web app exports OBJ files as a zip folder because web browsers have trouble saving multiple files at once. In the desktop app, the obj file, mtl file, and texture files are saved individually and can be manually zipped if required.
If you need help, you can ask on the Blockbench Discord server: https://discord.gg/blockbench
