### ISSUE TITLE
[Suggestion] Downscale exported OBJ models by 16

### ISSUE THREAD

**Issue by EwyBoy** [JannisX11/blockbench#496]
- Detailed description: 

When creating a new Java Block / Item and exporting it as a OBJ file they end up 16 times to large when loaded up in the game. JSON files work fine and scale corretly. But OBJ models end up 16 to large. Here is a example image: https://imgur.com/a/GvP2601
The values in the OBJ file tagged with the `v` tag needs to be divided by 16 for the model to have the correct scale. Doing this will scale the model correctly. I tested this.

But then the offset from the center and on the Y cordinate will be messed up becaue of the new reduced `v` values. So this has to be fixed to. I tried scaling my model down with a factor of 16 like this: https://imgur.com/a/xh5VU1t

Now my model has the correct scale in-game but the block appears negative 8 blocks down on the Y axis and half a block of on the negative x and z axis. Would be nice if you could fix this so I don't have to spend hours manualy calculating every value after exporting.

- Minecraft Version: 1.14.4
- Blockbench variant: Desktop
- Operating System: Windows 10 Pro

**Comment by JannisX11** [comment]
Blockbench models work in a 16x16 space. So in JSON models, 16 pixels equal one block in game. Whether OBJ models should keep the current 16x16 model space or be converted to a 1x1 space is a matter of interpretation and how the models appear in game depends on the software you use the load the OBJ models.

But I will keep this open as a Suggestion because resizing the OBJ model could definitely be the more convenient solution in the long run.

**Comment by EwyBoy** [comment]
Yes I understand that. But since the program has a tailored option to create a Minecraft block / item for the java edition it would be nice if the format it was exported to in line with how the stuff is rendered in game by default. Keep up the good work.

**Comment by JannisX11** [comment]
Implemented in 3.3.
