### ISSUE TITLE
[Issue] Local rotation rotates as Global rotation in Bedrock Entity

### ISSUE THREAD

**Issue by SykoUSS** [JannisX11/blockbench#720]
![start](https://user-images.githubusercontent.com/14918520/92312808-7840d580-ef92-11ea-910f-77dd3560e435.png)
![weird_rot](https://user-images.githubusercontent.com/14918520/92312809-78d96c00-ef92-11ea-868f-8b906aaac957.png)

When rotating anything it will always rotate as if Global is selected.

**Comment by SykoUSS** [comment]
Upon further testing it appear as though the x "works" for local rotation but not the y or z

**Comment by JannisX11** [comment]
Local rotation mode directly changes the euler rotation values of the object. However, these do not necessarily align with the axes of the rotation gizmo. This is because the axis rotations are applied it a specific order. You can find out more if you look up "Gimbal Lock". But because values are directly linked, this is a Works as Intended.
