### ISSUE TITLE
[Issue] Dissapearing head bone

### ISSUE THREAD

**Issue by violetskyzz** [JannisX11/blockbench#723]
Console Errors:
![Screenshot (19)](https://user-images.githubusercontent.com/71052407/92674258-f41c8400-f2ea-11ea-828f-58a6fac6d7d8.png)

I have created a model with animations. When I export the Item to a geo.json file and re-open it in blockbench, all blocks in the bone file "head" dissapear. The texture file also seems to dissapear (not just a "textue not found error but the texture is completley gone. When I save the model as a BBMODEL file and re-open it everything is fine.

-Blockbench 3.6.6 Desktop 
-Operating System: Windows 10 pro 18363.1016

.Json, .BBMODEL and .PNG file attatched:
![grindylownew](https://user-images.githubusercontent.com/71052407/92674805-195dc200-f2ec-11ea-957d-7c6cf1e58ff2.png)

[grindylownew.zip](https://github.com/JannisX11/blockbench/files/5198831/grindylownew.zip)

Thank you in advance
-VIoletskyzz

**Comment by JannisX11** [comment]
First of all, textures are not saved in the geometry file. If you create a custom entity, Blockbench will automatically load the textures associated with the entity, but if not, you have to load the textures manually

Regarding the disappearing cubes, apparently your cubes were set to NOT export. If you enable more options in the outliner ("Toggle More Options", F4), you can see the little camera icon next to cubes. If instead of this icon you see a gray box with an X inside, then export is disabled.
