### ISSUE TITLE
Problem with saving model

### ISSUE THREAD

**Issue by NeedHelpMe** [JannisX11/blockbench#807]
I created the "entity java" model, then saved it via "export as entity java" and closed the program. After a failed attempt to make this model a mob, I opened the model in the program and saw that half of the body was gone. Apparently it disappeared while still being saved. Tell me what the problem is and most importantly - how to return the lost part of the body. I spent a lot of time creating it, I'm a beginner.

**Comment by JannisX11** [comment]
Could you attach the .java file so that I can take a look?
.java is not a lossless format. Usually the importer does a pretty good job at opening the files again, but to save projects .bbmodel project files are the safer option.
If you are using the desktop app, you can also find the last 30 days of backups by clicking the button in the Help menu.
