### ISSUE TITLE
UV mapping to entity java mod Minecraft is not good for me.

### ISSUE THREAD

**Issue by tattoosfour** [JannisX11/blockbench#822]
Hello good, I have a problem I am exporting a java entity model to make an armor from a mod with Mcreator and I realized that the texture does not do the UV mapping well, I have recreated it several times and you always get your arms out. or the helmet or the chest with transparency, and consulted in the Mcreator forum and reached the conclusion that it is Blockbench, because I repeated the process several times, I just wanted to inform since I imagine that not only would it have happened to me.

I use windows 10 pro, amd fx 8000 series, 8gb ram, and 500 ssd hard drive.
Use Blockbench 3.7.5.

Following console warning.

language.js:72 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
desktop.js:100 Electron 8.5.2, Node 12.13.0
boot_loader.js:44 Three.js r120
boot_loader.js:45 Blockbench 3.7.5 Desktop (Windows)
plugin_loader.js:426 Loaded 2 plugins 
Array(2)
DevTools failed to parse SourceMap: file:///C:/Users/TATTO/AppData/Local/Programs/Blockbench/resources/app.asar/lib/gif.js.map
DevTools failed to parse SourceMap: file:///C:/Users/TATTO/AppData/Local/Programs/Blockbench/resources/app.asar/lib/VuePrismEditor.umd.min.js.map
DevTools failed to parse SourceMap: file:///peerjs.min.js.map

Photos.
[https://fotos.subefotos.com/1bd0385fb7c706259dbe4a2a39ab00a3o.jpg](url)
[https://fotos.subefotos.com/43657920f395bfe5c2e80f3446d1dca1o.jpg](url)

**Comment by JannisX11** [comment]
Please provide more information. I do not see any UV issues in the screenshot, and the Minecraft screenshot is too small to really see anything. Please upload the model and/or show exactly the issue you are experiencing.

**Comment by sk-minecraft** [comment]
@tattoosfour 
I also experienced the same issue for 1.15.2 and 1.16.4, if you try to export the Modded Entity (java) as a complete armor model, it will end up with the textures all over the place. Boots will be up to the leggings, leggings almost halfway up the chestplate, and the helmet will show textures that were not in the Blockbench model. In my case the chestplate never had an issue. 

At first I looked for a solution in MCreator (no solution found), then learned how to code using eclypse (focused on the armors only), same output. I must clarify, basic armors with common, 3d, PBR or POM textures have no issues. The issues is when a full 3d model armor is created, in Blockbench it will look perfect but using MCreator or coding it ... it will break (that is what I thought, but I was wrong). Once you are satisfied with your 3d armor, create a texture template (do not texturize/paint it yet), save everything, and test it in Minecraft. You will find yourself with a weird looking model, it is not the model ... it is the texture. UV mapping to be specific.

The solution I found is: 

Create every single portion separated (one for each; helmet, chestplate, leggings, and boots). It will be frustrating, or better say ... very frustrating, you may have to move the UV mapping several times. If your 3d armors are simple, they may be fast but if you go for complex designs ... it will take time to figure it out. In modded entity you won't be able to resize the UV mappings only move it. Instead of erasing and repainting it, I would recommend editing the texture until you get an idea where it should be. Try not to use the top left or center of the texture map, better go for far right and the bottom, that will reduce the textures interfering with each other. Once every portion of the texture is in place, then you can texturize your models. 
 
It may sound confusing, I only hope it can help.
Examples can be seen here:

[](https://www.planetminecraft.com/member/__sk__/)
