### ISSUE TITLE
[Suggestion] Provide a function to render to a canvas via JSON and png urls

### ISSUE THREAD

**Issue by MartinMuzatko** [JannisX11/blockbench#912]
Hello! I am trying to render a model in my own website/webapp. I am creating a web-based custom minecraft recipe finder.
Are there exported functions that one can use to render a model based based on JSON and png files?
These png files could be either provided via url - base64 encoded or path. JSON I would like to feed in directly.

I was browsing the source code but couldn't find anything related to render 3D models.
I would have assumed that https://github.com/JannisX11/blockbench/blob/master/js/preview/canvas.js could help, but there are no exported modules that could be consumable via commonjs or es6 modules.

There is some documentation about how to create these standardized 3D block renders with commands using blockbench, however I would like to inline or automate this process.

https://minecraft.fandom.com/wiki/Minecraft_Wiki:Standardized_views#Using_Blockbench

Thank you in advance!

**Comment by JannisX11** [comment]
The model reading and rendering is not modular, and there are no plans to make it modular since rendering is at the core of Blockbench, and separating it would make the program less efficient.

If you are looking for rendered images for your website, you can take screenshots in Blockbench, or automate that process using a custom plugin.
If you are looking at a real 3D model viewer, you can use [this model viewer](https://github.com/vberlier/json-model-viewer) for Minecraft Java Edition JSON models, [this one](https://github.com/bridge-core/model-viewer) for Bedrock Edition JSON models, or just setup a [three.js](https://threejs.org) renderer to render glTF models.
