### ISSUE TITLE
Rotation Bug with Blockbench

### ISSUE THREAD

**Issue by beanrollup** [JannisX11/blockbench#946]
Description of issue:
Sometimes when rotating a cube or bone manually (using the rotate tool), you get very specific decimal points instead of the expected + or - 2.5 degrees.
Up-to-date version. Pivot points are normal, they aren't on any decimals or anything. Doesn't seem to be rhyme or reason to which specific cubes or bones have this weird rotation bug.

Demo of bug:
https://youtu.be/kr43hK6GryI

**Comment by JannisX11** [comment]
Rotation angles are applied in a specific order. The rotate tool calculates the value of all axes in order to rotate on the current local axis, and in some cases it needs to modify the two other values in order to achieve the desired rotation. This was changed in 3.9 in order to prevent [gimbal lock](https://en.wikipedia.org/wiki/Gimbal_lock) related issues.
If you want to just change the value of an axis, you can use the sliders in the sidebar directly.
