### ISSUE TITLE
[Issue] No support for `bind_pose_rotation`

### ISSUE THREAD

**Issue by stirante** [JannisX11/blockbench#990]
When loading model of panda or polar bear, the body is rotated 90 degrees, because blockbench seems to ignore `bind_pose_rotation` value. This value seems to be rotating the cubes of the bone without rotating the bone itself.

I found an old issue about that #576, but decided to post another because it was closed without any comment about fixing it or not and I fear that comments to a closed issue might not receive an answer.

Version: 3.9.2
Variant: Website
Model format: bedrock geometry JSON

**Comment by JannisX11** [comment]
There are no plans to support this field in Blockbench. It only works in the legacy 1.8 format and is only used by some older vanilla Minecraft mobs. The feature is now redundant because cubes natively support rotations.
To load vanilla Minecraft mobs into Blockbench, we now have the Minecraft Entity Wizard plugin which uses the new format.
